// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ysaseremmlgrxlcpwhux.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlzYXNlcmVtbWxncnhsY3B3aHV4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM1MDM1MTAsImV4cCI6MjA1OTA3OTUxMH0.urrmy9YxeyZZVmNteMAVUQWuQnpoSXQ3xDDtJv87Was";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);